# Generated by Django 5.2.5 on 2025-08-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('demo_link', models.URLField(blank=True, null=True)),
                ('birthday', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('cv', models.FileField(null=True, upload_to='cv/')),
                ('city', models.CharField(max_length=100, null=True)),
                ('degree', models.CharField(max_length=50, null=True)),
                ('freelancer', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
