# Generated by Django 5.2.5 on 2025-08-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sub_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
