# Generated by Django 5.2.5 on 2025-08-27 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class, e.g., bi bi-code-slash', max_length=50, null=True),
        ),
    ]
